### ISSUE TITLE
/GW commands

### ISSUE THREAD

**Issue by lukejn123** [nsporillo/GlobalWarming#28]
we recently just installed this plugin on our server but whenever we perform the /gw commands nothing happens? were just wondering if this is a bug or you have to restart the plugin or something.

**Comment by nsporillo** [comment]
Can you paste your servers startup log to https://gist.github.com/ and share the link?

When you install GlobalWarming for the first time, the database connection doesn't work because the default credentials wont match most people use for their MySQL server.

Just recently I updated the code to allow for "demo mode" which allows everything to work on first install, except for data saving after restarts. I can compile the latest code and share that with you if you'd like to try out the plugin without using a MySQL database.

**Comment by BGHDDevelopment** [comment]
Having the same issue. 
I do get an error I believe it's related to the commands not working.
https://pastebin.com/GT5Bztfw

Once this is fixed I can make a youtube tutorial of plugin :)

**Comment by nsporillo** [comment]
Thank you noodles. Did you upgrade from a previous version or fresh install? 

I’ll get this fixed tonight or tomorrow. I appreciate your interest in making a YouTube tutorial, that would be very useful and I’d be glad to feature it on the project pages.

**Comment by BGHDDevelopment** [comment]
It was a fresh install.

**Comment by nsporillo** [comment]
Okay thank you. That’s embarrassing. Seems like that bug was hidden by my development environment.

I’ll work on fixing it.


—————————————— 
Nick Porillo

**Comment by nsporillo** [comment]
@BGHDDevelopment @lukejn123 I've discovered the issue. Luckily it is fixable on your end, but I will also publish a fix for it. The problem is the entity types that are defined in the model file contain some added in 1.14 but when I backported the code to 1.13 I forgot to remove them. Also when I tested, I tested with the latest 1.14 spigot. Sorry about this.

This fix was made here: https://github.com/nsporillo/GlobalWarming/commit/724ca7014e5b2a07612dde292ed460f56bc68fc9

You can make this change on your own, but I'll be uploaded this fix as well.

**Comment by lukejn123** [comment]
We're using a 1.12.2 server and I'm wondering if this has any form of relation to the bug?

**Comment by lukejn123** [comment]
(also bukkit)

**Comment by nsporillo** [comment]
@lukejn123 Someone else posted an error that I think will fix yours. Try the latest file found here:
https://www.spigotmc.org/resources/global-warming-in-minecraft.63381/download?version=274346

The last error I fixed was https://github.com/nsporillo/GlobalWarming/issues/29 , which occurred due to specific server setups that did not use 'world' as the default world name. We were missing error checking and handling for those cases, but it should be working now.

**Comment by lukejn123** [comment]
thanks

**Comment by lukejn123** [comment]
still not working? something to do with mySQL database I think [ERROR] [GlobalWarming] MySQL connection not found.

[ERROR] [GlobalWarming] Data won't persist after restarts!

[ERROR] [GlobalWarming] Please update config.yml and restart the server.

[ERROR] Error occurred while enabling GlobalWarming v1.0.1 (Is it up to date?)

java.lang.NullPointerException: null

at net.porillo.config.WorldConfig.loadKeys(WorldConfig.java:54) ~[?:?]

at net.porillo.config.ConfigLoader.load(ConfigLoader.java:52) ~[?:?]

at net.porillo.config.WorldConfig.<init>(WorldConfig.java:30) ~[?:?]

at net.porillo.engine.ClimateEngine.loadWorldClimateEngines(ClimateEngine.java:37) ~[?:?]

at net.porillo.GlobalWarming.onEnable(GlobalWarming.java:87) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.2.jar:git-Bukkit-2b93d83]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by lukejn123** [comment]
> Can you paste your servers startup log to https://gist.github.com/ and share the link?
> 
> When you install GlobalWarming for the first time, the database connection doesn't work because the default credentials wont match what most people use for their MySQL server.
> 
> Just recently I updated the code to allow for "demo mode" which allows everything to work on first install, except for data saving after restarts. I can compile the latest code and share that with you if you'd like to try out the plugin without using a MySQL database.

guessing I need this?

**Comment by nsporillo** [comment]
@lukejn123 Please update to the latest version. Also, if you want to just try out GlobalWarming before setting up a MySQL server you can ignore the first warning. It's only necessary if you want data to be saved after shutdown.

Regarding the other error you posted, it's because you're running an old version that did not do error checking on the world association. We support multi-world, but we wanted to allow for a consistent carbon score across all worlds you want. That's why world_nether is "associated" with world, so players don't just go to the nether to do smelting. 

Please go into the world configs that were generated after you update and set the associations properly. I should probably look into a way to do this automatically or maybe with a command.

**Comment by nsporillo** [comment]
@lukejn123 Also, feel free to join the discord to ask for support too: https://discord.gg/favAKt

**Comment by Fireworkstars46** [comment]
> @lukejn123 Also, feel free to join the discord to ask for support too: https://discord.gg/favAKt

The link doesn't work for the discord?
